### ISSUE TITLE
`echo -e` is not POSIX-compliant

### ISSUE THREAD

**Issue by Denton-L** [LinuxStandardBase/lsb-samples#2]
In `sb_release/src/lsb_release`, the shebang that's declared is `#!/bin/sh` which is usually a POSIX-compliant shell. However, there are many instances of `echo -e` which [are not POSIX-compliant](https://pubs.opengroup.org/onlinepubs/9699919799/).

We should either switch the shebang to `#!/bin/bash` or, even better, switch the `echo -e` to `printf` invocations [which should be POSIX](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/printf.html).

I'm not sure if this repo is even active anymore but if it is, I'd be happy to submit a PR.

**Comment by mwichmann** [comment]
Still active? Not really, to be honest.

I think your `printf` approach is better.  Shouldn't really force `bash`, not everyone uses it, there are a lot of shells around and although it might be surprising for a system not to have bash at all, it could happen.
